/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtnTest: typeof import('./src/components/elementui/btn-test.vue')['default']
    ComponentItem: typeof import('./src/components/componentItem/index.vue')['default']
    ConfigProvider: typeof import('./src/components/elementui/config-provider.vue')['default']
    DraggableApp: typeof import('./src/components/componentItem/draggableApp.vue')['default']
    DraggableGroup: typeof import('./src/components/componentItem/draggableGroup.vue')['default']
    DraggableIndex: typeof import('./src/components/componentItem/draggableIndex.vue')['default']
    DraggableMovePark: typeof import('./src/components/componentItem/draggableMovePark.vue')['default']
    DraggableSort: typeof import('./src/components/componentItem/draggableSort.vue')['default']
    DraggableTable: typeof import('./src/components/componentItem/draggableTable.vue')['default']
    DraggablsBase: typeof import('./src/components/componentItem/draggablsBase.vue')['default']
    DragTest: typeof import('./src/components/componentItem/dragTest.vue')['default']
    DrButton: typeof import('./src/components/package/dr-button/index.vue')['default']
    DrButtonGroup: typeof import('./src/components/package/dr-button-group/index.vue')['default']
    DrButtonIcon: typeof import('./src/components/package/dr-button/slots/dr-button-icon.vue')['default']
    DrButtonLoading: typeof import('./src/components/package/dr-button/slots/dr-button-loading.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElIntput: typeof import('element-plus/es')['ElIntput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IndexApp: typeof import('./src/components/myInput/indexApp.vue')['default']
    InputGroup: typeof import('./src/components/myInput/inputGroup.vue')['default']
    InputSub: typeof import('./src/components/myInput/inputSub.vue')['default']
    MyInput: typeof import('./src/components/myInput/index.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
